### ISSUE TITLE
I had a couple of issues -- but ultimately got it to work!

### ISSUE THREAD

**Issue by htoddt** [cmallwitz/Financials-Extension#1]

**Comment by htoddt** [comment]
1.  When I attempt to run test_yahoo.py before compiling I got:
Import Error: No module named 'com' (or 'com.financials.getinfo.Financials' is unknown)

I didn't try test_google.py

2. When I compiled, I saw an error that idlc was not found.

3. When I imported the compiled extension I got an error that pytz was not found.

I suggest you update your readme to indicate that:
LibreOffice SDK needs to be installed (Maybe it's obvious to most; but it wasn't to me.
Add pytz to your list of required packages
Finally, compile first then run your tests.

Thank you for this work.  After working through the issues I opened the sample spreadsheet and it worked!

Awesome job!

**Comment by cmallwitz** [comment]
I added the missing *.oxt file to https://github.com/cmallwitz/Financials-Extension/releases/tag/1.0.3 because you shouldn't be required to build this yourself (even though you managed)

Can you let me know what environment you use (OS/Python/OpenCalc version)? The Support tab in examples.ods has a call to reviel some further details.

I should update the project README.md accordingly...

**Comment by htoddt** [comment]
ctx=pyuno object (com.sun.star.uno.XComponentContext)0x55b294b4e7c0{, supportedInterfaces={com.sun.star.uno.XComponentContext,com.sun.star.container.XNameContainer,com.sun.star.lang.XTypeProvider,com.sun.star.uno.XWeak,com.sun.star.lang.XComponent}}
uname=Linux 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64
sys.executable=/usr/bin/python3
sys.version=3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]

I didn't see these on the support tab so from Calc Help:
LibreOffice Version: 6.0.7.3
Build ID: 1:6.0.7-0ubuntu0.18.04.5

$python3 --version
Python version:  3.7.3

**Comment by htoddt** [comment]
Sorry, didn't mean to close...
