### ISSUE TITLE
Yahoo only showing price correctly, change X 100, nothing (?) for any other requests

### ISSUE THREAD

**Issue by Durhammer3111** [cmallwitz/Financials-Extension#101]
As of this morning, I'm only getting the current price (21) and % change (11) -- though that appears to be 100X what it should be -- and nothing for market cap, P/E, Beta, dividend or EPS data.  And the downloaded web pages look really weird.

Edit: oh yeah -- the downloaded web pages have a link labeled "Back to Classic".

5PM -- Still the same, but it did look like the last time it ran (couple of hours ago), not all prices came down, and ONE (the last ticker in the sheet) stock did have a value for Beta. WEIRD.

**Comment by dtw2000** [comment]
I was getting N/A on previous close(5) and oddities with % change(11) with Yahoo.  Someone in the other issue thread mentioned that Yahoo was A/B testing data.  I can echo that I might get a %change of 5% for a stock then reload the shared document on a different machine that was on a hot spot and get a 500% change.  I was setting a reference cell as a multiplier for all my Yahoo reference stocks.  That got old quickly.  My better workaround was to build a separate table and focused on minimizing calls, working out some data points based on current price (21) and price change (7).  It may be a penny off or so, but it works well for me now if Yahoo is needed for a given stock symbol.  From those 2 data points you can calculate the ~Previous Close and then you can calculate ~%change.  That probably won't get you around all the missing yahoo data points.

**Comment by cmallwitz** [comment]
Closing this - please try new version 3.6.1
