### ISSUE TITLE
LibreOffice 24.2.2.2, Windows 10.0 Build 19045 and Financials -Extension 3.4.0 not working

### ISSUE THREAD

**Issue by myllo** [cmallwitz/Financials-Extension#104]
This combination does not work. 

trace.log shows just on line per item, ie
2024-04-30 11:59:37.802198 getRealtime *args=('SPYD.DE', 5.0, 'YAHOO') r='None' 833.691 ms

extension.log is empty.

**Comment by schmani-db** [comment]
Have you tried the 3.5.0 already which is available here? That could maybe help.
However, since 2 weeks I only get N/A for all requests even when using the 3.5.0. - I believe Yahoo must have changed something once again.

**Comment by myllo** [comment]
I had not noticed the 3.5.0 been released.

However, the outcome with version 3.5.0 is the same - #N/A. No changes in the logs.
