### ISSUE TITLE
=GETHISTORIC("IBM",90,"2020-12-01","YAHOO") has an error

### ISSUE THREAD

**Issue by omoknen** [cmallwitz/Financials-Extension#11]
Using LO Windows 6.4.7.2 (x64)
Get GETREALTIME command works, but GETHISTORIC command doesn't work.
We received an error in the cell of:

Date format not supported: '2020-12-01'

We can not figure out why that happened.  We tried alternate dates and symbols still the same error.
I wish I knew something about Python.
I did check the error message and I know it is about "dateutil"  and I checked it is installed in LO.

We looked at the download on the page and that date format looks the same.
Is there something we can change?  Thank you

**Comment by cmallwitz** [comment]
Assuming you use a recent version, could you check file extension.log in directory .financials-extension under the current users home directory if it contains any usable error message? What is your Windows language?

**Comment by omoknen** [comment]
Using Windows 10 Pro English, I decided to put both a getrealtime and a gethistoric on a single sheet.

The "extension.log" had nothing, so I looked at the "trace log" and it had the same kind if messages.

2021-01-01 14:00:51.794242 getRealtime *args=('IBM', 21.0, 'YAHOO') r='125.88' 2099.483 ms
2021-01-01 14:00:51.794242 getHistoric *args=('IBM', 90.0, '2020-11-01', 'YAHOO') r='Date format not supported: '2020-11-01'' 0.115 ms
2021-01-01 14:00:51.794242 getRealtime *args=('IBM', 21.0, 'YAHOO') r='125.88' 0.033 ms
2021-01-01 14:00:51.794242 getHistoric *args=('IBM', 90.0, '2020-11-01', 'YAHOO') r='Date format not supported: '2020-11-01'' 0.097 ms
2021-01-01 14:01:03.518853 getRealtime *args=('DIS', 21.0, 'YAHOO') r='181.18' 1105.451 ms

**Comment by cmallwitz** [comment]
I have uploaded a new release of the extension to fix this issue (I hope) - let me know if that works for you. For the record, the was the (normal) Python locale not being set on Windows.

**Comment by omoknen** [comment]
Thanks it worked - you worked so fast!

I saw that in the release about the locale, since all my settings are defaulted in LO it must take it from the OS.  That was probably the problem.

**Comment by cmallwitz** [comment]
Good to know! closing...
