### ISSUE TITLE
URL with control characters

### ISSUE THREAD

**Issue by tkswe88** [cmallwitz/Financials-Extension#112]
When running =GETREALTIME("SE0015660014",21,"FT") the following message is printed 
"FT.getRealtime(SE0015660014, 21) - urlopen endpoint: URL can't contain control characters. '/data/equities/tearsheet/summary?s=ACRI A:STO' (found at least ' ')"
It was great, if you could fix this issue.

Thanks for the nice extension!

**Comment by cmallwitz** [comment]
Try new release [3.6.3](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.6.3)

This actually adds a workaround for FT incorrectly triggering HTTP redirects to URLs that should have been properly URL-encoded on their side but aren't....

**Comment by tkswe88** [comment]
Thanks a lot! Now it works like a charm.
