### ISSUE TITLE
Problem with price / currency conversion

### ISSUE THREAD

**Issue by cmallwitz** [cmallwitz/Financials-Extension#13]
Also Im notice the bug,
=GETREALTIME("MCX:MOEX";21;"GOOGLE") returns the value 15726, this is result without comma, real value is 157,26 rub.

_Originally posted by @ikyquocked in https://github.com/cmallwitz/Financials-Extension/issues/10#issuecomment-770029872_

**Comment by cmallwitz** [comment]
Could you copy&paste output from =GETREALTIME("SUPPORT") ?

Additionally there should be a file in your user/home directory, folder .financials-extension with name "google-MCX:MOEX.html" - Could you attache this as well ?

This maybe a system or LibreCalc language setting issue. When I run the above I get 157.62

**Comment by ikyquocked** [comment]
=GETREALTIME("SUPPORT")
```
ctx=pyuno object (com.sun.star.uno.XComponentContext)0xc49d40{, supportedInterfaces={com.sun.star.uno.XComponentContext,com.sun.star.container.XNameContainer,com.sun.star.lang.XTypeProvider,com.sun.star.uno.XWeak,com.sun.star.lang.XComponent}}id(self)=334941896version=2.5.0file=C:\Users\Danila\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu121561j767.tmp_\Financials-Extension.oxt\financials.pycwd=C:\Program Files\LibreOffice\programhome=C:\Users\Danilauname=Windows GIGABYTE 7 6.1.7601 AMD64 Intel64 Family 6 Model 94 Stepping 3, GenuineIntelpid=5992sys.executable=C:\Program Files\LibreOffice\program\soffice.binsys.version=3.7.7 (default, Dec 10 2020, 19:56:54) [MSC v.1925 64 bit (AMD64)]locale=(None, None)defaultlocale=('ru_RU', 'cp1251')
--

```
No such file like "google-MCX:MOEX.html", i see only "google-MCX" and "google-MOEX" and they are 0 bytes size. Ive started to using yahoo, its correct.

**Comment by ikyquocked** [comment]
Sarepta Therapeutics stock makes error 
2021-02-01 21:42:42.692400 getRealtime *args=('srpt', 21.0, 'yahoo') r='Yahoo.getRealtime(srpt, 21) - urlopen: ('https://finance.yahoo.com/quote/srpt?p=srpt', 404)' 3544.451 ms

**Comment by ikyquocked** [comment]
Attaching js of tbioa.me with currency bug
[yahoo-tbioa.me.js.txt](https://github.com/cmallwitz/Financials-Extension/files/5906066/yahoo-tbioa.me.js.txt)
string 56    ['fromCurrency', None]
string 84 ['currency', None],
string 102    ['fromCurrency', None],

**Comment by cmallwitz** [comment]
It is odd: Yahoo is showing USD in text on page but their data JSON block has currency as None. Not helpful! I have tried to mitigate this with a new release 2.5.1
Have a look and let me know how that works for you.

**Comment by ikyquocked** [comment]
Thank You so much, cmallwitz! Now it works perfect =)
