### ISSUE TITLE
Question: How may one pull data from a specific date in recent past?

### ISSUE THREAD

**Issue by lin-b-github** [cmallwitz/Financials-Extension#14]
The extension works well for me for pulling the data offered. 

Is there a way to pull historical data to compare with the current data?

For example, I'm wanting to compare stock prices (current) to a specific date in the recent past (14 December 2020, or the closest trading day to it).

**Comment by cmallwitz** [comment]
Historic data is only available from Yahoo. Check out the Readme and the examples for function GETHISTORIC. It takes a date as argument and it is your responsibility to define the "recent past" taking into account weekends and/or trading holidays.

**Comment by lin-b-github** [comment]
Thank you, @cmallwitz . That's exactly what I was seeking. Much appreciated.
