### ISSUE TITLE
Number of shares

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#15]
Do you see a way to add number of outstanding shares?

**Comment by dio-source** [comment]
Are you asking for how many total shares a company has available?

**Comment by casper43** [comment]
Yes. Basically what =GoogleFinance(A24, "shares") does in Googlespreadsheets.

**Comment by dio-source** [comment]
=IF("AAPL:NSQ"=0,"",GETREALTIME("AAPL:NSQ",27,"FT"))

**Comment by casper43** [comment]
That would get the total market capitalisation (Number of shares x LAST_PRICE) I Could calculate them. But sometimes there are numbers missing.

**Comment by dio-source** [comment]
Share price x outstanding shares = market cap so...
Market cap / share price = outstanding shates.

=IF("AAPL:NSQ"=0,"",GETREALTIME("AAPL:NSQ",27,"FT")) divided by share price

**Comment by casper43** [comment]
Yes, I just did that. Thanks.
There are some PE_RATIOS missing, for instance: =GETREALTIME("SIKA:SWX";"PE_RATIO";"FT"). Is there a workaround?

**Comment by cmallwitz** [comment]
Excellent - new issue and I don't have to work the answer out - Thanks !:-)

Re: missing PE ration

Checking [https://markets.ft.com/data/equities/tearsheet/summary?s=SIKA:SWX], it seems it is missing on website too so unfortunately I can't do anything about it.

**Comment by casper43** [comment]
@cmallwitz: Can you make a unique ticker symbol instead of your solution in the example (which demands an extra sheet)? 
I currently use the FT ticker which is a cell in my calc-sheet, but there are some PE Ratios missing with FT (as seen). And it would be great to have fall back on Yahoo or Google if that's the case.

**Comment by cmallwitz** [comment]
That is difficult: it would need some sort mapping/database between RIC / ticker / SEDOL / ISIN . This would have to be maintained somehow as it could be changing due to corporate actions like mergers, company renaming themselves etc.

I have got the same issue and do a vlookup in a separate sheet depending on source (yahoo/google/ft) using data I put together for the assets I use.

**Comment by dio-source** [comment]
@cmallwitz I just want to say thank you very much for this extension so i dont have to use google crap. Do you accept donations? I only have a few dollars but the least i can do is buy you a coffee.

**Comment by cmallwitz** [comment]
no donations required :-)

I needed something like it and because nothing else would quite work, I built it myself. As long as the extension is useful (and mostly works) for other people, I'm fine too.

**Comment by dio-source** [comment]
@cmallwitz Let me at least buy you a coffee. It's a really nice piece of software and helps me out a lot. I will also look into libreoffice extension programming to see if I can contribute.

**Comment by casper43** [comment]
Since this morning I receive following error by accessing the FT codes: <Datacode.TIMESTAMP: 999> in Libre. What could it be?

I add on to these. It's great stuff you are putting together. Coldn't wrap my head around vlookup though.

**Comment by cmallwitz** [comment]
Re: "Datacode.TIMESTAMP: 999" - could be  problem with the data on page - can you give us complete formula incl. symbol?

**Comment by casper43** [comment]
=GETREALTIME("DHR:NYQ";"LAST_PRICE";Source)

**Comment by cmallwitz** [comment]
seem to work for me - have you tried re-calculating CTRL-SHIFT-F9 ? if that doesn't fix it I would need to see the DHR files from the .financials-extension directory under your home directory.

**Comment by casper43** [comment]
Refreshing didn't work out.
[ft-DHR:NYSE.zip](https://github.com/cmallwitz/Financials-Extension/files/5964378/ft-DHR.NYSE.zip)

**Comment by casper43** [comment]
Surprisingly closing the file and reopening it from nautilus helped.

**Comment by casper43** [comment]
Hi, can you provide the number of outstanding shares with Financial Times? I currently calculate this, but unfortunately that's a problem if you need these in formulas.

**Comment by casper43** [comment]
Also: I get a faulty result with BRBY:LSE (FT) by dividing market_cap through last_price, it states 4 million shares then, but they have actually 404.84 Mio. :-)

**Comment by cmallwitz** [comment]
That last issues here looks like a problem with price quoted in GB pence and market cap in GB pounds.

**Comment by casper43** [comment]
Any news on getting the current number of outstanding shares from somewhere? In order to calculate the real market cap on the fly.

**Comment by cmallwitz** [comment]
Closing this for now
