### ISSUE TITLE
EX_DIV_DATE : Can you provide it with a calc date format?

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#16]
It seems that EX_DIV_DATE doesn't come in a readable calc date format to run formulas on it. In my case it would be neat to run some conditional formatting on it (I'd like to highlight the upcoming EX_DIV_DATES). 

Should be straightforward to change. Any plans?

**Comment by cmallwitz** [comment]
I can format cells with the ex div date as "Date" in format "1999-12-31". When I then e.g. do +1 or -1 against those cells, the date is correctly reflected. So what is not working for you?

**Comment by cmallwitz** [comment]
Having said that I'm struggling to get any conditional formatting to work with dates...

**Comment by casper43** [comment]
Clicking on the date-format button in calc won't change anything. The date always displays the same (e.g. 2020-04-12). I also tried to make a reference in another cell to the date and format these reference cells as date. Couldn't get any date calculations that way (substracting one date from another).

**Comment by cmallwitz** [comment]
I tried to do something like this: one cell contains e.g. '=GETREALTIME("IBM",72,"YAHOO")' - the another cell says ={this ex-div date cell}+30 . then I see another date 30 later than the first. This looks to be working for me?

**Comment by casper43** [comment]
Yes, this seems to work. I can't format the specific original cell as a date though. Maybe that's the reason why conditional formating doesn't work?

**Comment by cmallwitz** [comment]
Closing this for now
