### ISSUE TITLE
FT: Israeli company

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#17]
Couldn't access any price data of this one, although the data seems there: https://markets.ft.com/data/equities/tearsheet/summary?s=DELT:TLV

**Comment by cmallwitz** [comment]
Confirmed - I get some data but not prices - I will take a look.

**Comment by cmallwitz** [comment]
New version published - this should be fixed now.

**Comment by casper43** [comment]
Cool. I can confirm it.
