### ISSUE TITLE
Installation of Python 3 libraries in Arch Linux

### ISSUE THREAD

**Issue by Dodobeard** [cmallwitz/Financials-Extension#19]
I can confirm that this extension also works nicely in Arch Linux. I just installed

- python-pyparsing
- python-dateutil
- python-pytzdata
- python-pytz

like so
_sudo pacman -S python-pyparsing python-dateutil python-pytzdata python-pytz_
and then the OXT file installed without issues.
A simple test without loading the rather large example file is this formula:
_=GETREALTIME("IBM:NYQ";"OPEN";"FT")_

**Versions:** LibreOffice 7.1.0.3 10(Build:3); Financials-Extension 2.6.0

**Comment by cmallwitz** [comment]
Thanks for the feedback.

**Comment by cmallwitz** [comment]
Closing - new version 3 should not require any additional installation steps.
