### ISSUE TITLE
TOM:FRA

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#21]
I just discoverd that =GETREALTIME(Ticker;"MARKET_CAP";Source) for TOM:FRA get's a faulty result. This might have to do with currency conversion. You can compare it with TM:NYQ (Japan).

**Comment by cmallwitz** [comment]
Issue confirmed - I will have to take a look - maybe it gets confused with some reference to Yen some place but but I can't immediately see where...

**Comment by cmallwitz** [comment]
Looks like the (all the German at least) exchanges, have market cap in JPY rather then in quoted currency (EUR). The number is really that big in JPY :-)

Compare:
https://markets.ft.com/data/equities/tearsheet/summary?s=7203:TYO 
vs
https://markets.ft.com/data/equities/tearsheet/summary?s=TOM:FRA
vs
https://markets.ft.com/data/equities/tearsheet/summary?s=TM:NYQ

Not sure if we can do something (sensible) about it...

**Comment by casper43** [comment]
There seems the problem. If the number of shares would be obtainable one could calculate market cap. This seems missing so I currently do the opposite: I calculate the number of shares by dividing the Market_Cap through price.

**Comment by cmallwitz** [comment]
Closing this for now.
