### ISSUE TITLE
Table calculations

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#22]
Whenever I wan't to include a row or a value in calc it takes ages, till I can enter the value (document is loading in the background, obvisiously from at this moment not necessary background calculations of your plug-in). Can I disable this behaviour somehow?

**Comment by cmallwitz** [comment]
More of a Libre/OpenOffice question: I found this too (at least assuming we are talking about same thing) - Calc call the extension but from the extension perspective there is zero control over what Calc is doing while fetching data. Calc will call one cell at a time, one after another.

Now if you have two symbols - one valid one and one invalid one and get 5 data points for them, the extension will fetch all information for a symbol if it can and subsequent calls to other data points for same symbol will use cached information. But for the invalid symbol, I can't tell why it was invalid. so with every additional data point referenced from Calc there will be another network round trip to check if data is available which slows everything down. For instance this is taking most of the time it takes to open example.ods (looking for symbol NONAME)

**Comment by casper43** [comment]
If I add a row with no information in it at all, it's also present. At this point the text I enter in the cell has not become a symbol for any calculation yet. So IMO it's not about invalid symbols. Probably we need a way to suppress that calc is calling the extension until it's necessary by entering data anywhere in the sheet.

**Comment by cmallwitz** [comment]
Closing this for now
