### ISSUE TITLE
Data not collected

### ISSUE THREAD

**Issue by fran-can** [cmallwitz/Financials-Extension#23]
Thank you for your work .  I am using Windows 10 and Libre Office 7.1.2.2.  I have a small problem with the Yield data being collected  for  ETFs.  The Yield information  shows on  Yahoo Finance HTML  but  does to make it to the spreadsheet . For example, recently the HTML sheet for  SCHD shows a yield of 2.87%   but that data does not appear on the  Realtime sheet.

**Comment by cmallwitz** [comment]
Issue confirmed: Looks like the yield for ETFs is in different field. I will need to take a closer look.

**Comment by cmallwitz** [comment]
Try the new release version 3.0.3 and please confirm if that fixes the issue you reported.
