### ISSUE TITLE
Exchange rate conversion

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#25]
Do you have a solution to converting a price from dollars into pounds?

**Comment by cmallwitz** [comment]
Yes - have a look into the example ODS file - both Yahoo and FT publish FX conversion rates

**Comment by cmallwitz** [comment]
In order to see what is available from FT, try to search here: https://markets.ft.com/data/currencies/tearsheet/summary?s=USDGBP (link is already pointing to USD/GBP rate)
