### ISSUE TITLE
This ticker symbol is broken

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#26]
Probably due to the used space character:
https://markets.ft.com/data/equities/tearsheet/summary?s=NOVO%20B:CPH

Btw: Any news on calculating market cap on the fly?

This site gives detailed information (see financials under any ticker): https://www.marketscreener.com/quote/stock/CISCO-SYSTEMS-INC-4862/?type_recherche=rapide&mots=cisco Where are they getting their data from?

**Comment by cmallwitz** [comment]
I have uploaded version 3.0.1 - let me know if that fixes this issue for you.

**Comment by cmallwitz** [comment]
Re: market screener data - a paid data feed? I would assume whoever is feeding them price data is providing this extra information for next to nothing. Might be quite some work to structure it properly and keep track of currency issues in financial data.

**Comment by casper43** [comment]
I can confirm that your update fixes it. Thx.

Would be nice to get this info as well if they get it for next to nothing. :) At the moment I copy my data from there and enter it manually.
