### ISSUE TITLE
Pulling down historic prices from Yahoo

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#28]
How do I enter a LSE quoted co into the pull formula yahoo 90. (It did not give the correct price)

Am I correct in assuming that Yahoo does not have a history of UK LSE quoted companies?

**Comment by cmallwitz** [comment]
It should work e.g. data is available here: https://uk.finance.yahoo.com/quote/VOD.L/history?p=VOD.L

See examples.ods "Historic Examples"

**Comment by R7914T** [comment]
Thank you for checking.   I have it working now.
