### ISSUE TITLE
Market Cap for HYU:DEU missing

### ISSUE THREAD

**Issue by casper43** [cmallwitz/Financials-Extension#30]
See above. Did your endeavours to look for a reliable provider (life market cap, etc) yield any results?

**Comment by cmallwitz** [comment]
If you try HYU on the FT web site, it looks like a Euro listing is available as HYU:BER

(And, no - I'm not currently looking to add another data provider)

**Comment by casper43** [comment]
But not market cap. I get #NV with =GETREALTIME(Ticker;"MARKET_CAP";Source) .

**Comment by cmallwitz** [comment]
Because it isn't available on https://markets.ft.com/data/equities/tearsheet/summary?s=HYU:BER either

What is your use case for getting market cap from secondary exchanges instead of just using the primary exchange of a particular equity and (using an additional FX lookup) convert that to any currency you need?

Even prices from secondary exchanged don't strike me as particular useful - prices may not be comparable to primary exchange due to low volume or larger spreads...

**Comment by casper43** [comment]
Hi. Every source is from a secondary exchange. As FT doesn't seem to have the original (Hyundai is a South Korean car manufacturer) available.

Not sure how to do FX lookups.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
cmallwitz ***@***.***> schrieb am Mittwoch, 30. Juni 2021 um 15:01:

**Comment by cmallwitz** [comment]
Then try Yahoo - either (in different currencies)
    https://uk.finance.yahoo.com/quote/005380.KS?p=005380.KS&.tsrc=fin-srch 
or
    https://uk.finance.yahoo.com/quote/HYMTF?p=HYMTF&.tsrc=fin-srch

The file examples.ods in the "Release" area here on GitHub has FX lookup examples.

**Comment by casper43** [comment]
Okay, my whole doc is refering tickers to a source cell currently. Have you found Yahoo more reliable than FT?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
cmallwitz ***@***.***> schrieb am Mittwoch, 30. Juni 2021 um 15:56:

**Comment by cmallwitz** [comment]
Based on my experience Yahoo and FT have similar reliability. While Yahoo has more symbols/exchanges (e.g. Hyundai on South Korean exchange in this example and/or US option details), FT is faster for me mainly (I reckon) because it is closer (I'm in London too).

**Comment by casper43** [comment]
Thanks for your answer. That market cap isn't calculating the "current" market cap on the fly, makes your plugin not very usable however for calculating fundamentals.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
cmallwitz ***@***.***> schrieb am Mittwoch, 30. Juni 2021 um 16:27:

**Comment by cmallwitz** [comment]
Well, I can't make up the numbers if they aren't available :-)

But I guess even if I add "shares outstanding" as a field, the quality of it would be the same: is it really shares outstanding / total share number or  some "free float". Additionally it could be different from exchange to exchange on only updated once or twice a year...

**Comment by casper43** [comment]
I assume we need a reliable datasource for this. Google has it. The power of your plugin pretty much depends on reliable data. :)

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
cmallwitz ***@***.***> schrieb am Montag, 5. Juli 2021 um 11:06:

**Comment by cmallwitz** [comment]
Closing this for now.
