### ISSUE TITLE
Ubuntu 20.04 Nothing in extenson Manager

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#33]
I moved the  spreadsheets using Financial-Extensions (F-E)  to a new location. 

All my entries in my spreadsheets using the extension now show the function expanded and they no longer work for example:

=IF(G24="cash",0,com.financials.getinfo.python.financialsimpl.getrealtime($G24,39,"ft"))/1000

The extension manager is showing no extensions.

 I have tried to reinstall F-E by adding in F-E.oxt to libreoffice calc. I get the error message:

/home/robin/.config/libreoffice/4/user/uno_packages/cache/ -uno_packages/lu1327wv315c.tmp_/Financials-Extensions.qxt does not exist

I thought I had it installed by changing the oxt file quality, but it has disappeared. 

I have checked my backups and nothing is being restored for config/libreoffice...

On starting a new spreadsheet I have checked the Basic Macro Organiser. It does **not** show that the F-E macro has been installed in the library

**Comment by cmallwitz** [comment]
I'm away from computer but if you have no other extension, maybe just delete the uno-packages directory completely, restart LO and reinstall extension.

On a related note: I have never seen the function name prefixed with "
> com.financials.getinfo.python.financialsimpl" maybe try a global find/replace to remove this  and see if that fixes things
...

22 Aug 2021 15:40:22 R7914T ***@***.***>:

**Comment by R7914T** [comment]
before writing I replaced one of the pulls, but it reverted to the string I posted.

**Comment by R7914T** [comment]
I am trying to understand what has gone wrong. So far I have reinstalled libreoffice, and am trying to reinstall the extension but I keep getting the error message I quoted in the opening post to this query.

Looking at your readme, I find the comment 

"Additionally, starting with version 3 of the extension, it contains all non-standard Python packages it uses (dateutil, pytz, pyparsing). Consequently, it is no longer necessary to install anything to your system."

But later on in the same readme it states:

"Build:

You will need the LibreOffice SDK installed.

On my system (Ubuntu) I installed packages: libreoffice-dev libreoffice-java-common libreoffice-script-provider-python

# depending on your location...

cd ~/tech/IdeaProjects/Financials-Extension/

python3 -m unittest discover src

# This builds file Financials-Extension.oxt

./compile.sh
Tested with:

    Windows 10 / LibreOffice Calc 7.1.2.2 / Python 3.8.8
    Ubuntu 20.04 / LibreOffice Calc 6.4.3.2 / Python 3.8.2"

As  I am using 20.04 does this mean I need to install those items mentioned, even though you advise nothing needs to be installed on the system?

R

**Comment by R7914T** [comment]
As I am anxious to get my share summary system working again, I have unsuccessfully followed the build instructions:

`root@robins-desktop:/home/robins/tech/financial-extension# python3 -m unittest discover src
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.8/unittest/loader.py", line 346, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: 'src'
root@robins-desktop:/home/robins/tech/financial-extension# 

`

**Comment by cmallwitz** [comment]
You don't need to build the extension. The result will just be the same Financials-Extention.oxt file you can download from GitHub anyway.

22 Aug 2021 22:56:36 R7914T ***@***.***>:

**Comment by cmallwitz** [comment]
So what error are you getting installing the extension. In your earlier post you said

"/home/robin/.config/libreoffice/4/user/uno_packages/cache/ -uno_packages/lu1327wv315c.tmp_/Financials-Extensions.qxt"

Where is it getting the extension qxt from?

22 Aug 2021 22:56:36 R7914T ***@***.***>:

**Comment by R7914T** [comment]
I have just downloaded the oxt ext from your site on github. I put it into a directory under home. Checked that it was executable. 

From the Ext Manager I tried to add the oxt file in, but the error message states that it does not exist in the uno_packages temp dir. 

I also tried 2X clicking the file on the disk. Ext manager opens it but gives the same error message.

**Comment by R7914T** [comment]
I tried to install it manually by placing the oxt file into a sub dir with the same name and path as in the error message as above. 

I can see it in  the ext manager but it has an error: the status of this extension is unknown.

When I clicked on the enable button it stated:

Insert duplicate implementation name 
com.financials.getinfo.python.FinancialsImpl
  (Button for ok when clicked does not install)

**Comment by R7914T** [comment]
I have it working. I found a backup of the .config/ libreoffice directory. I deleted it on the HD and then restored the backup. Without deleting it was unable to restore the F-E files, so some of the problem must have been to do with permissions but it did not look like it when I examined the directory settings. I checked the drive structure. There were no errors. 

Otherwise, I do not know why I could not reinstall without resorting to the backup.

**Comment by cmallwitz** [comment]
This is difficult to assess without some error message.

If you have a backup of the local extension folder, maybe it would be safe if you can check if you can remove the extension from Extension Manager and re-add it again - but it sounds more like a LO rather than extension problem.



23 Aug 2021 02:26:22 R7914T ***@***.***>:

**Comment by cmallwitz** [comment]
Closing this in the meantime...
