### ISSUE TITLE
BlackRock Gold and General Fund D AccGB00B5ZNJ896:GBP

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#34]
At 31/8/21 at 9:12 BST I am not getting any prices on this link. How do you suggest I work around it?

**Comment by cmallwitz** [comment]
Checking https://markets.ft.com/data/funds/tearsheet/summary?s=GB00B5ZNJ896:GBP

and using =GETREALTIME("GB00B5ZNJ896:GBP",21,"FT")

I get a price. Can you double check on your side?

**Comment by R7914T** [comment]
I did not check that price as I use other ones in your list, but I have adjusted the spreadsheet to bring it in, if those others are not available. Thank you. In those circumstances I have found the IFS function particularly helpful as it greatly simplifies coding for choices.
