### ISSUE TITLE
Missing FT stats

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#37]
I notice that the FT also shows shares outstanding and Free float. If you have time could you please add them into the extension's options.

**Comment by cmallwitz** [comment]
Unfortunately only if you are registered/logged in.

**Comment by cmallwitz** [comment]
Sorry - my fault was looking for something else. shares outstanding and free flat is something that could be done for yahoo/ft. I will take a look.

**Comment by cmallwitz** [comment]
I have publish a new version of the extension 3.0.5 with SHARES_OUT and FREE_FLOAT data points. Let me know if that works for you.

**Comment by R7914T** [comment]
Thank you very much for making the additional stats available.

I could not find a readme file  setting out all the codes now available in your extension.

I keep the list of codes in the notebook "ZIM" but I had difficulty copying and pasting the list from github into Zim. It came out poorly formatted and hard to read quickly. Instead I first copied them into libreoffice and then copied and pasted the block of entries in libreoffice into Zim. That caused each column to be straight.

I will start using the new stats and if there is a problem I will let you know.

Thank you again,

**Comment by R7914T** [comment]
Currently, my spreadsheet is not showing any values for the two new data points. I have tried both F9 and ctrl shift F9. Other data points are working.

I have updated the extension with version 3.0.5.

**Comment by cmallwitz** [comment]
Hmmm... Could you try the examples.ods spreadsheet from [https://github.com/cmallwitz/Financials-Extension/releases/tag/3.0.5] and see if you see data? Maybe you have switch between FT and Yahoo in the sheet first.

**Comment by R7914T** [comment]
The  example spreadsheet is showing shares out and free float results, even though the function in your examples point to the field name  instead of the code. I therefore dug further and found that the newly added  cols in my spreadsheet were not showing the values because of something connected with the cell formats. I cleared direct formatting. The function results appeared and then could be formatted  and still show the correct results. In other words sorry to have raised the query.
