### ISSUE TITLE
Err:504 in every cell

### ISSUE THREAD

**Issue by wilx** [cmallwitz/Financials-Extension#4]
I have managed to build and install your extension but the example document gives me `Err:504` for every cell. I am not sure what to do and how to debug this. Any ideas?

![Screenshot_2020-05-14_18-48-07](https://user-images.githubusercontent.com/1098563/81962261-c57bee80-9613-11ea-9347-0e9054838085.png)

**Comment by wilx** [comment]
The extension has created `$HOME/.financials-extension` directory but there are no files in the directory.

**Comment by cmallwitz** [comment]
1) This is odd - what system/distro are you using (LibreOffice 6.4 seems fairly new)? 
2) Can you check the last tab "Support" - is that displaying any information?

Cheers

**Comment by wilx** [comment]
Odd. In the mean time, I have restarted once and it seems it started working. This is Ubuntu 20.04 LTS.

```
ctx=pyuno object (com.sun.star.uno.XComponentContext)0x5591123b3590{, supportedInterfaces={com.sun.star.uno.XComponentContext,com.sun.star.container.XNameContainer,com.sun.star.lang.XTypeProvider,com.sun.star.uno.XWeak,com.sun.star.lang.XComponent}}
id(self)=140464678394272
version=2.0.0
file=/home/wilx/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu2724436ysomj.tmp_/Financials-Extension.oxt/financials.py
cwd=/home/wilx
home=/home/wilx
uname=Linux amber2 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64
pid=288369
sys.executable=/usr/bin/python3
sys.version=3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
```

**Comment by cmallwitz** [comment]
Bummer - it would have been nice to know how to handle that better. I will set up a Ubuntu 20.04 VM to have a look. Thanks!
