### ISSUE TITLE
extension still works after uninstall

### ISSUE THREAD

**Issue by gb13717** [cmallwitz/Financials-Extension#42]
Hello - Your extension got me playing the python scripting and I ultimately made a python script that calls livecoinwatch's api to give me crypto prices. So, I no longer need your extension.
So I uninstalled it and removed all the calls to =GetRealTime()

But strangely your extension still works even though I uninstalled it. I forgot about remove a call to GetRealTime() and it was automatically changed to:
=com.financials.getinfo.python.financialsimpl.getrealtime()

just an fyi in case there is something related to the uninstall process you can/want to fix. 
take care and thanks again for your extension!

**Comment by cmallwitz** [comment]
Maybe the spread sheet still "knows" what it should call or was calling when seeing a function call that wouldn't work any more. But the extension install / uninstall is completely handled by LO. I'm not sure if LO physically deletes the extension or just removes it from the list of registered extensions. In the later case it may even keep working...

Nothing I can do here though! Thanks
