### ISSUE TITLE
Direction of calc

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#44]
When filling a spreadsheet with your yahoo/ FT functions I would like all the rows to be filled  before the Columns. Is that the current method?

**Comment by cmallwitz** [comment]
The order of calls to the extension is completely outside of my control: LC is calling the extension first downwards (rows) and then going to the right (next columns) where it goes down first again before moving to any further column

Note: We did discuss order of processing in this [issue](https://github.com/cmallwitz/Financials-Extension/issues/38)
