### ISSUE TITLE
BlackRock Gold and General Fund D Acc    GB00B5ZNJ896:GBP

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#48]
As I have not found the above in Yahoo  I use FT as the price source: 

Today the extension  is not getting the price from FT, instead  of the price it reports: 

Datacode.timestamp.999

These are  the calc entries that were  working yesterday:
=GETREALTIME(C$10,"21","ft")

C10 is GB00B5ZNJ896:GBP

Are you able to replicate the problem?

**Comment by cmallwitz** [comment]
Can't replicate it - I get the same price as on
https://markets.ft.com/data/funds/tearsheet/summary?s=GB00B5ZNJ896:GBP

Anything in {user home idrectory} /.financials-extension files
extension.log ?

**Comment by R7914T** [comment]
There was too much in the log so I deleted the content. Turned off the computer. Upon restarting the error disappeared. Thank you for your help.

Robin
