### ISSUE TITLE
"Industry" as a field is required

### ISSUE THREAD

**Issue by hellkaim** [cmallwitz/Financials-Extension#5]
Hi,
There is a data regarding the company's industry sector.
Of what I know for Yahoo with python-yahoo lib one can acquire it by using the code alike
```
import yfinance as yf

sbux = yf.Ticker("SBUX")
tlry = yf.Ticker("TLRY")

print(sbux.info['sector'])
print(tlry.info['sector'])

```
Could you please add that field in the available data codes? If only for Yahoo it will also be ok.

PS. HUGE THANKS for such a nice and powerful extension. I dono why LO does not have that as MS EXcel has it out of the box... and what for are spreadsheets anyway if not for financial markets.

**Comment by cmallwitz** [comment]
Let me take a look what can be done about it. Thanks Christian

**Comment by cmallwitz** [comment]
I've uploaded a new release - do you want to check it out? https://github.com/cmallwitz/Financials-Extension/releases/tag/2.1.0

It supports sector and industry for Yahoo and FT, but the values you get are not very consistent (and I have seen them change)

**Comment by hellkaim** [comment]
Wow!
That's so grate! Yes, I'll check it out and got back to you.
