### ISSUE TITLE
Auto-Update

### ISSUE THREAD

**Issue by Andresmith76** [cmallwitz/Financials-Extension#51]
Hello - I just found your extension and really appreciate your efforts. I've created a spreadsheet listing numerous stocks - how can I get the getrealtime cells to start auto-updating on a regular basis? Thank you!

**Comment by cmallwitz** [comment]
Unfortunately, I'm not aware of an automatic way to trigger a refresh but you can press key CTRL-SHIFT-F9 to force an refresh manually.

**Comment by Andresmith76** [comment]
Thank you! A very helpful suggestion added to a wonderful piece of work. :>)
