### ISSUE TITLE
GETREALTIME Command

### ISSUE THREAD

**Issue by Andresmith76** [cmallwitz/Financials-Extension#52]
If I create a spreadsheet containing numerous cells using the GETREALTIME command, is there a way to disable those commands when the file is saved, preserving the data collected for future reference? I want a spreadsheet that will fetch individual stock statistics each day and then save the collected data for future viewing, comparison, etc. without automatically updating every time the file is reopened.

**Comment by cmallwitz** [comment]
Unfortunately I don't know of any way to accomplish this.

**Comment by jbourvic** [comment]
Perhaps save the document as a pdf. If it is for reference, there is no need for the data to change.

**Comment by Andresmith76** [comment]
Thank you -  that is what I ended up doing. Saving each daily spreadsheet as a PDF for static future reference.

**Comment by cmallwitz** [comment]
Closing now.
