### ISSUE TITLE
Love It

### ISSUE THREAD

**Issue by noisland1** [cmallwitz/Financials-Extension#54]
Thanks for all the hard work!!  Using on LibreOffice 7.3.2.2(x64) to screen and track div payers.  Only suggestion so far would be to add https://iexcloud.io/markets/ as replacement for google. Downside is limit to number of free queries (but I've never hit it.)

**Comment by cmallwitz** [comment]
Thanks - re: iexcloud.io - this doesn't seem to be a good replacement for anything. it only seems to have US stocks - no FX and no international markets.

**Comment by noisland1** [comment]
Didn't know FX and international markets were needed. Am only using for US markets to track dividend growth stock. Grateful for this tool, its the only one that I've found.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by phrwn** [comment]
Just jumping in here to also say thanks for making this. I just found it today and as well as looking up prices I've used it to _finally_ make a formula that calculates the last trading day of the month. Please keep it alive and thank you!

**Comment by cmallwitz** [comment]
Closing issue for now.
