### ISSUE TITLE
GETREALTIME Yahoo Down? 

### ISSUE THREAD

**Issue by Andresmith76** [cmallwitz/Financials-Extension#57]
Yesterday and today (6/1 & 6/2), after I open my spreadsheet all my GETREALTIME statements to Yahoo display #N/A. Is Yahoo not available or have I broken my spreadsheet?

**Comment by cmallwitz** [comment]
Yahoo apparently has changed their cookie management. A new release
https://github.com/cmallwitz/Financials-Extension/releases/tag/3.0.7 is
available which seems to address the issue successfully.

**Comment by Andresmith76** [comment]
Success! Very impressive how quickly you were able to analyze the problem, create and post the solution. My posted issue is now resolved. Thank you!
Andre'
