### ISSUE TITLE
GETREALTIME(...,"YAHOO") is broken

### ISSUE THREAD

**Issue by trougnouf** [cmallwitz/Financials-Extension#58]
GETREALTIME is currently broken with YAHOO. I get #N/A results.
Switching to GETREALTIME(..., "FT") works (but then I don't get cryptocurrencies).

**Comment by cmallwitz** [comment]
Please try new Version 3.0.7 - Thanks.

6 Jun 2022 18:57:02 Benoit Brummer ***@***.***>:

**Comment by trougnouf** [comment]
Thank you! Sorry I forgot about manual updates; signed up for new release notifications.
