### ISSUE TITLE
Sometimes wrong asking price / offer price is being downloaded from yahoo

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#59]
It is rather difficult to give examples because it seems to only happen with some shares and not consistently.
I have noticed that this formula is not bringing down the latest ask price shown on yahoo:

=GETREALTIME("ASTO.L",25,"yahoo") 

Today it was showing 830 when it was higher on the yahoo  site.

**Comment by cmallwitz** [comment]
It is indeed difficult to say what or if something is wrong.

Looking at daily chart for ASTO.L though and it had a low/high of 801/900p today. Could it be the price was just very volatile?

Take a look at the full screen chart and you see it was very "jumpy" today.

23 Jun 2022 17:03:47 R7914T ***@***.***>:

**Comment by cmallwitz** [comment]
Let's first look at this from the extensions perspective - using TPG.L on Yahoo as example
- in your home directory a file ".financials-extension/yahoo-TPG.L.html" will contain the response it received from Yahoo
- the first line in the file is the actual URL that was requested - 'https://finance.yahoo.com/quote/TPG1.L?p=TPG.L' 
- a second file in the same location "yahoo-TPG.L.js" will contain a data block extracted from the HTML 
- whatever numbers are in there will be passed back through extension
- if that file contains the numbers you are seeing in the spread sheet, the extension is working as expected

Now let's look at data flow from London Stock Exchange to Yahoo (or any other web site you may be looking at). The raw data published by the exchange will be send to exchange subscribers (Yahoo, Financial Times, most banks, anybody else) - the data will include quotes with bid/ask changes and/or executed trades with prices. This data is at least 15 minutes delayed for non-paying (public) customers - this includes Yahoo. There will be additional delays inside Yahoo before data is available on their website for you to see (this delay is probably short but different for any of the website you are comparing). 

Now looking at TGP.L itself (I have access to the private, real-time LSE data) - reviewing the data I would categorize TGP.L as volatile and only lightly traded:
 
- 13:00-14:00 11 bid/ask updates, 7 trades executed (@ 1.2p to 1.365p), bid/ask spread from 0.05p to (massive) 0.3p 
- 14:00-15:00 no bid/ask updates, 2 trades executed (@ 1.36p & 1.362p), bid/ask spread unchanged
- 15:00-16:00 1 bid/ask update, 1 trade executed (@ 1.362p), bid/ask spread still 0.2p

You mentioned a time of 14:04 - going back 15 minutes, the public information would have been a bid/ask of 1.1/1.3p with a last traded price of 1.27p - this correlates with what you mentioned above and it seems Yahoo was fairly "correct" 

I hope this makes any sense - not the most straight forward thing to wrap ones head around...

**Comment by cmallwitz** [comment]
Closing this for now
