### ISSUE TITLE
Issue when installing extension

### ISSUE THREAD

**Issue by aradum** [cmallwitz/Financials-Extension#6]
Hi, just tried installing the extension (version 2.1.0) and Libre Office returns the following :

(com.sun.star.uno.RuntimeException) { { Message = "<class 'SyntaxError'>: invalid syntax (financials.py, line 51), traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 102, in getModuleFromUrl\X000a    codeobject = compile( src, encfile(filename), \"exec\" )\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

Running latest stable Libre Office 6.3.6.2 on Windows 10.

**Comment by cmallwitz** [comment]
Sorry for the late response. I don't have access to a Windows box right now but this user got it to work on Windows after installing a few Python packages - see https://github.com/cmallwitz/Financials-Extension/issues/3#issuecomment-578574607

It is worth checking if the latest Libre Office is actually using Python 3 in which case you may want to install Python 3 modules.

**Comment by ChemicalRascal** [comment]
This looks like a different error (after confirming that LO is using Python 3 and has the right modules installed, the error still appears). It actually looks like it's a syntax error, in:

https://github.com/cmallwitz/Financials-Extension/blob/99c660f1adf259c39bd9e2d780f96f72402409e0/src/financials.py#L50-L52

Dumping the formatted string py3 interpreter on Windows also throws a syntax error. Throwing it IDLE does _not_. (Or, well, it stops complaining after everything is defined, but whatever.)

Manually editing the release to exclude 50-52 reveals a similar error in the following:

https://github.com/cmallwitz/Financials-Extension/blob/99c660f1adf259c39bd9e2d780f96f72402409e0/src/google.py#L94-L95

So, despite all my better judgement screaming at me to not, I'm inclined to say that for some reason that syntax... for _some_ reason trips up on Windows installs of Python. For _some_ reason. Not that that makes even the slightest lick of sense, of course.

**Comment by ChemicalRascal** [comment]
Ooooh. Found the issue.

`C:\Users\James>"c:\Program Files\LibreOffice\program\python.exe" --version`
`Python 3.5.7`

LibreOffice on Windows doesn't have Python 3.6 in their stable release. Which is when f-strings were added, apparently.

Updating from LO 6.4.7 to LO 7.0.2 gives:

`C:\Users\James>"c:\Program Files\LibreOffice\program\python.exe" --version`
`Python 3.7.7`

And after installing the requisite packages (again), the extension installs just fine.

**Comment by cmallwitz** [comment]
These formatted strings f"...{..}..." are a recent Python 3.6 addition and I was assuming as all LO installations I ever came across are above that it would be safe to use. Maybe I should add a version check if your fairly recent Windows LO was still using Python 3.5

Thanks for getting at the root cause for this!

**Comment by ChemicalRascal** [comment]
No worries!

**Comment by aradum** [comment]
Seems to work now. However I needed to install the dateutil module manually for LibreOffice.
