### ISSUE TITLE
How to: IBOVESPA - SA

### ISSUE THREAD

**Issue by chavesfop** [cmallwitz/Financials-Extension#60]
Sample URL:
https://finance.yahoo.com/quote/ITSA4.SA?p=ITSA4.SA

Sample command: 
`=GETREALTIME("ITSA4.SA"; "LAST_PRICE"; "YAHOO")`

Current Result:
```
ITSA4.SA current price
```

**Comment by cmallwitz** [comment]
Closing this for now.
