### ISSUE TITLE
LibreOffice Calc Issue

### ISSUE THREAD

**Issue by Andresmith76** [cmallwitz/Financials-Extension#62]
I've been using the GETREALTIME statements in LibreOffice Calc daily now for many months to retrieve real-time stock quotes using Yahoo Financial and haven't had any issues until now. Starting last Friday, Nov. 4, my entire spreadsheet display's N/A instead of each cells stock data. Has something changed with the website that would require me to alter each cell statement? 
Here's an example of how my statements are parsed: 
=GETREALTIME("KO",21,"YAHOO")

**Comment by cmallwitz** [comment]
Please download/install new version of the extension. Thanks

**Comment by Andresmith76** [comment]
I have followed your instructions but still have the same issue. After I started the newest extension install, I received the following error message:
(com.sun.star.uno.RuntimeException) { { Message = "<class 'FileNotFoundError'>: [Errno 2] No such file or directory: \"C:\\\\Users\\\\Andre'\\\\AppData\\\\Roaming\\\\LibreOffice\\\\4\\\\user\\\\uno_packages\\\\cache\\\\uno_packages\\\\lu95366m9p94.tmp_\\\\Financials-Extension%203.08-Nov%202022.oxt\\\\financials.py\", traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 146, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 93, in getModuleFromUrl\X000a    with open( filename, encoding='utf_8' ) as fileHandle:\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by Andresmith76** [comment]
Wait a minute - I changed the name of the extension file after downloading but before installing. After I changed the name back to its original, the installation worked without the error message. All is OK now - sorry for the confusion. Thank you!

**Comment by cmallwitz** [comment]
Ah - yes - an annoying LibreOffice habit. An extension file is basically a zip archive. But somehow the name of the archive before everything gets extracted matters...

**Comment by Andresmith76** [comment]
It appears this issue has returned - I had the same problem described above last week. When I downloaded and installed your latest update Financials-Extension-3.09, that fixed it - but it has returned again. This seems to be a reoccurring issue. As 1st mentioned, I am using the GETREALTIME statement to retrieve assorted stock information to update my spreadsheet. Am I using LibreOffice in a way that is forcing Yahoo Finance causing this statement to break?
Thank you for you help!

**Comment by cmallwitz** [comment]
Confirmed - YAHOO changed their web site quite a bit earlier this weekend - already on it making necessary changes...

**Comment by cmallwitz** [comment]
I uploaded version 3.2.0 to fix Yahoo - can you check if it works for you (there are some fields that are not fixed yet) ?

**Comment by cmallwitz** [comment]
I just pushed release version [3.2.1](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.2.1) fixing a few outstanding issues. Have a look and let me know if I missed anything!

**Comment by Andresmith76** [comment]
Preliminary checks show my previous issues have now been rectified/repaired with 3.2.1.
Thank you again for all your quick work and efforts!
Andre'

**Comment by cmallwitz** [comment]
Let me close this - any other issue, raise another item!
