### ISSUE TITLE
[SOLVED] Can't get historic data for TQQQ

### ISSUE THREAD

**Issue by phrwn** [cmallwitz/Financials-Extension#65]
`=GETHISTORIC("TQQQ",90,$B20,"YAHOO")`
B20 has the date.

It works fine with MVV which I'm using elsewhere, but not TQQQ, even though Yahoo does have historical data for both.

What am I doing wrong?

**Comment by cmallwitz** [comment]
I pulled data for last week for TQQQ and received data with the exception of Thursday 24 Nov when exchanges were closed for Thanksgiving. Which date don't you get TQQQ data for?

**Comment by phrwn** [comment]
Thanks for having a look. It seems it's not the date that's the problem; it's four-character tickers. The above formula works fine with three-character tickers. With TQQQ, MSFT, or AAPL for example it outputs variations of:
`Yahoo.getHistoric(TQQQ,90,2019-09-30) - crumb`

**Comment by AD-Wright** [comment]
I can say I'm also having this issue, but with XMR-USD, another more-than-three-letter ticker.  It works fine for dates before 2022-10-06, but spits out a similar `Yahoo.getHistoric(XMR-USD, 16, 2022-10-07) - crumb` message for seemingly any date after.

**Comment by phrwn** [comment]
It's doing it with three-letter tickers: VOO any date after November 2nd, 2022 is producing the same error. Must be Yahoo.

**Comment by cmallwitz** [comment]
I don't think it has anything to do with the length of the symbol.

I have been trying to reproduce something the last couple of days on my side - but no success: I always get the data. I think (based on your error message) the best I can do at the moment is adding more logging/tracing information around it and then wait for you guys to report back some more details.

In the meantime you could close LibreCalc completely, open only the examples.ods from the Releases section here and see if that works for you.

**Comment by AD-Wright** [comment]
Ah - I just realized I was running one version behind on the extension, sorry.  Updating (removing and re-adding the extension) appears to have resolved the "crumb" issue for me.

However, I will note that the "example.ods" file also freezes LibreOffice for me.  

OS: Ubuntu 20.04.4 LTS
LibreOffice:
Version: 7.4.2.3 / LibreOffice Community
Build ID: 382eef1f22670f7f4118c8c2dd222ec7ad009daf
CPU threads: 6; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Flatpak
Calc: threaded

**Comment by phrwn** [comment]
Ah! Removing and re-adding has solved all crumb issues here too. It said there were no updates, but I see it's gone from 3.0.7 to 3.0.8 now and it works.
