### ISSUE TITLE
Financial Market Extension 3.0.8 stopped working

### ISSUE THREAD

**Issue by dr-oxner** [cmallwitz/Financials-Extension#68]
I used the Financial Market Extension 3.0.8 pulling "last price"data from yahoo. It worked well but suddenly I only get the message #N/A.
When re-running the application by pressing [CTR+SHIFT+F9] the turning cirlcle spins for a while but no data are updated.
My OS is WIN7. 
Here the formula (example): =GETREALTIME("UL",21,"YAHOO")
Result #N/A
I re-installed libre office - no change.
I deleted and re-installed the extension - no change.
Any suggestion what I can do to fix the issue?

**Comment by cmallwitz** [comment]
Please get the new version 3.0.9 from the [Release](https://github.com/cmallwitz/Financials-Extension/releases) section

**Comment by dr-oxner** [comment]
Thanks a lot for your super-fast reply and help. It worked like a charm :)
