### ISSUE TITLE
Financials-Extension V.3.2.1

### ISSUE THREAD

**Issue by HitVideo2** [cmallwitz/Financials-Extension#73]
Get Dividend info (code 69, 70 & 71) from Yahoo is Not Working correctly in Windows 10 and LibreCalc 7.4.3.2. 
Returns nothing, not N/A, 0, or "".
Try: ACR, LUMN, PFX, REM, WBD

**Comment by cmallwitz** [comment]
REM is a fund without dividend information (see https://finance.yahoo.com/quote/REM?p=REM) but I get div yield value from the visible on the page.

The others stocks don't pay dividends either e.g. https://finance.yahoo.com/quote/WBD?p=WBD but I can see the PE ratio from the page.

**Comment by HitVideo2** [comment]
Whatever is returned from Yahoo can't be tested or used in formula for "", 0, or NA.Sent from my T-Mobile 4G LTE Device

-------- Original message --------
From: cmallwitz ***@***.***> 
Date: 12/29/22  1:47 PM  (GMT-07:00) 
To: cmallwitz/Financials-Extension ***@***.***> 
Cc: HitVideo2 ***@***.***>, Author ***@***.***> 
Subject: Re: [cmallwitz/Financials-Extension] Financials-Extension V.3.2.1
  (Issue #73) 


REM is a fund without dividend information (see https://finance.yahoo.com/quote/REM?p=REM) but I get div yield value from the visible on the page.
The others stocks don't pay dividends either e.g. https://finance.yahoo.com/quote/WBD?p=WBD but I can see the PE ratio from the page.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/cmallwitz/Financials-Extension/issues/73#issuecomment-1367577647",
"url": "https://github.com/cmallwitz/Financials-Extension/issues/73#issuecomment-1367577647",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by HitVideo2** [comment]
Even when a stock quits paying dividends, the extension should return SOME
value that can be tested (i.e. ", 0, NA) in LibreCalc cells.


On 12/29/2022 at 1:47 PM, cmallwitz ***@***.***> wrote:



REM is a fund without dividend information (see
https://finance.yahoo.com/quote/REM?p=REM) but I get div yield value from the
visible on the page.

The others stocks don't pay dividends either e.g.
https://finance.yahoo.com/quote/WBD?p=WBD but I can see the PE ratio from the
page.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by cmallwitz** [comment]
Extension is returning N/A when no value is available and if I try the formula

`=IF(ISNA(GETREALTIME("REM",70,"YAHOO")), "ISNA:TRUE", "ISNA:FALSE")`

I will get different output depending on whether value is N/A or not - I tried 70 and 71 as codes.

**Comment by HitVideo2** [comment]
Thanks, that is a solution I hadn't thought about.

IF I change the formulas in my spreadsheet to the following with relative cell
references then all combinations of function codes and with/without Dividend $
& % and PE ratio works.


=IF(ISNA(GETREALTIME("LUMN",70,"YAHOO")), 0, GETREALTIME("LUMN",70,"YAHOO"))

I will close the issue ticket. Thanks again





On 12/31/2022 at 9:29 AM, cmallwitz ***@***.***> wrote:



Extension is returning N/A when no value is available and if I try the formula

=IF(ISNA(GETREALTIME("REM",70,"YAHOO")), "ISNA:TRUE", "ISNA:FALSE")

I will get different output depending on whether value is N/A or not - I tried
70 and 71 as codes.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by HitVideo2** [comment]
BTW...ETFs seem to display Dividend Date and Amount from the "Historical Data"
link on the "https://finance.yahoo.com/" site.

Yield(Dividend) is on the Summary link. I don't know what else is a reliable
clue for ETFs other than in the Title.




Also, I have my spreadsheet updated with the current mods in case you'd like a
copy.








On 12/31/2022 at 9:29 AM, cmallwitz ***@***.***> wrote:



Extension is returning N/A when no value is available and if I try the formula

=IF(ISNA(GETREALTIME("REM",70,"YAHOO")), "ISNA:TRUE", "ISNA:FALSE")

I will get different output depending on whether value is N/A or not - I tried
70 and 71 as codes.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>
