### ISSUE TITLE
Yahoo getHistoric does not work

### ISSUE THREAD

**Issue by gikari** [cmallwitz/Financials-Extension#8]
I tried to put this into the cell to get the price of the stock on the specified day:
```
=GETHISTORIC("AAPL", "LAST_PRICE", "2020-10-13", "YAHOO")
```
And this returned the result:
```
Data doesn't exist - 21
```
But on https://finance.yahoo.com/quote/AAPL there is some data for the stock price on the specified day.

`GETREALTIME` function, however, works.

**Comment by cmallwitz** [comment]
LAST_PRICE is not supported for historic data. Supported fields for historic data are:

Field | Code
-- | --
OPEN | 6
LOW | 14
HIGH | 16
VOLUME | 35
CLOSE | 90
ADJ_CLOSE | 91

Have a look at the examples in examples.ods, tab "Historic Examples". Thanks for giving the extension a try!
