### ISSUE TITLE
Yahoo GETREALTIME Statements . . . Again

### ISSUE THREAD

**Issue by Andresmith76** [cmallwitz/Financials-Extension#80]
Looks like Yahoo has changed their website again as the GETREALTIME command is now broken. I'm running LibreOffice v. 7.3.2.2

**Comment by cmallwitz** [comment]
It is still working for me - can you provide an example symbol/formula? Try restarting your LibreCalc completely before... Thanks

**Comment by Andresmith76** [comment]
I opened LibreOffice and saw #N/A on this (an other similar) statements:
=GETREALTIME("T",101,"YAHOO")

**Comment by lorenzosplabs** [comment]
other examples not working ( OO version : 7.4.4.2, OS: OSX 12.6.2, financial extension ver 3.2.1) 

GETREALTIME("ADBE",21,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"    

GETREALTIME("ADBE",90,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'" 

GETREALTIME("ETH-USD",21,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"    

GETREALTIME("ETH-USD",90,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"

**Comment by Durhammer3111** [comment]
I opened issue #77 days ago with pretty much the same symptoms. I'll be happy to share any and all logs if you wish.

**Comment by Andresmith76** [comment]
Don't fret - cmallwitz is always awesome at taking care of these issues quickly!

**Comment by cmallwitz** [comment]
I have published a new version that hopefully addresses some shortcomings. Please close LibreCalc completely and use either a blank/new spreatsheet or the attached examples.ods to see if the extension is working in general or there is a problem with you spreadsheet itself.

**Comment by partimer** [comment]
Swapping get_cookies() values in financials_yahoo.com with the values from my firefox browser seemed to get this working for me (US IP to US Yahoo).  However this does require a recompile and extension reinstall.
`    def get_cookies(self):
        return [
            cookie("A1", "[REDACTED]"),
            cookie("A3", "[REDACTED]"),
            cookie("A1S", "[REDACTED]"),
            cookie("maex", "[REDACTED]"),
            cookie("PRF", "[REDACTED]"),
            cookie("thamba", "[REDACTED]")
        ]`

**Comment by cmallwitz** [comment]
I changed the cookie stuff so you can now edit a text file in ~/.financials-extension/yahoo.cookiejar

Having said that I have tested the extension using while VPNed to the US and pulling S&P 500 symbols so I'm wondering something else is going on ?

**Comment by Andresmith76** [comment]
THANK YOU! Updating with 3.3.0 did solve my reported issues.

**Comment by Durhammer3111** [comment]
Same here -- THANKS!!!

**Comment by spacecatz03** [comment]
Woohoo! Working once again, thank you!

**Comment by oldschool001** [comment]
Yep, working. Love this extension. Is there a way I can send $20 to cmallwitz to help support this?

**Comment by rodericklm1** [comment]
> other examples not working ( OO version : 7.4.4.2, OS: OSX 12.6.2, financial extension ver 3.2.1)
> 
> GETREALTIME("ADBE",21,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"
> 
> GETREALTIME("ADBE",90,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"
> 
> GETREALTIME("ETH-USD",21,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"
> 
> GETREALTIME("ETH-USD",90,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"

I just downloaded the latest version, and I am having this same issue.

**Comment by Durhammer3111** [comment]
> > other examples not working ( OO version : 7.4.4.2, OS: OSX 12.6.2, financial extension ver 3.2.1)
...
> 
> I just downloaded the latest version, and I am having this same issue.

Did you REMOVE the old extension before loading in the new one?

**Comment by cmallwitz** [comment]
This doesn't make much sense to me:

> GETREALTIME("ADBE",21,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"
> GETREALTIME("ADBE",90,"YAHOO") - output "Yahoo.getRealtimeSummary(ADBE, 21) - process: 'NoneType' object has no attribute 'findall'"

90 is CLOSE price for historical data but you are calling it with GETREALTIME and the error references 21 (LAST_PRICE) ? What is happening ?

**Comment by Durhammer3111** [comment]
Well, it's also outputting the same (ADBE,21) stuff for his ETH-USD queries! Seems to be stuck on ADBE, period.

**Comment by Leodivinci** [comment]
Was having same NA issue with extension running windows 11. Ran Libre Office as administrator and problems went away

**Comment by cmallwitz** [comment]
Closing this - new version 3.6.1 is out
