### ISSUE TITLE
YAHOO GETREALTIME/GETHISTORIC seems to be broken again

### ISSUE THREAD

**Issue by Hamalx** [cmallwitz/Financials-Extension#87]
For the last few days I have been receiving error messages for YAHOO quotes again:

getHistoric *args=('SLV', 90.0, 45107.0, 'YAHOO') r='Yahoo.getHistoric(SLV, 90, 2023-06-30) - crumb missing' 
getRealtime *args=('SLV', 21.0, 'YAHOO') r='None'

**Comment by cmallwitz** [comment]
Try the latest release - there was an update for Yahoos cookies...

**Comment by Hamalx** [comment]
I am on version 3.3.1 and realtime quotes are not working at all, historic quotes sporadically:

getHistoric *args=('META', 90.0, 45092.0, 'YAHOO') r='281.829987'
getHistoric *args=('META', 90.0, 45103.0, 'YAHOO') r='Yahoo.getHistoric(META, 90, 2023-06-26) - crumb missing'

Is there a newer one?

**Comment by cmallwitz** [comment]
Can you try deleting (user home directory) .financials-extension /
yahoo.cookiejar and then restart LibreCalc?

**Comment by Hamalx** [comment]
Perfect, works. Thank you for your help
