### ISSUE TITLE
Plugin return an error for some ticker codes.

### ISSUE THREAD

**Issue by aradum** [cmallwitz/Financials-Extension#9]
I am getting an error :

Yahoo.getRealtime(ZAG.TO, 21) - urlopen: 'charmap' codec can't encode character '\lx84' in position 346446: character maps to <undefined>

When trying to get the last price for ticker ZAG.TO and also for QQQ. It seems to work for every other ticker codes I tried so far.

Any idea what might be causing this?

Cheers !

**Comment by cmallwitz** [comment]
I tried from my side and it looks like I can get ZAG.TO and QQQ last prices without problem. Having said that it doesn't mean that there wasn't an issue when you tried with the content returned by https://finance.yahoo.com/quote/ZAG.TO?p=ZAG.TO and https://finance.yahoo.com/quote/QQQ?p=QQQ which could have tripped up the plugin code picking up the data from the pages.

I usually try to press CTRL-SHIFT-F9 after a few minutes which triggers a re-fetch of data to check if problem goes away or check URLs like the one above if I get any proper data.

Maybe I can see if I can capture errors better in the log file (Linux location) ~/.financials-extension/trace.log

**Comment by aradum** [comment]
Thank you for your reply. Re-fetching the data doesn't seem to work. Moreover this issue is there for me since I installed the plugin a couple of months ago. For now it only happens with these ticker codes. If I change for another ticker code, the cell return a normal price value.

In my browser, the links you posted work. I'm currently on Windows 10, using Libre Office 7.0.3.1.

I must add that the issue might be bigger than that on my system, as for me, only Yahoo seems to work with the plugin (when it works). When using Google, all ticker codes return the same kind of error, and when using FT, it displays _<Datacode. TIMESTAMP: 999>_

When looking at the HTML files generated by the plugin in users/user/.financials-extension/, the QQQ and ZAG files are empty and at 0KB.

Here is the entry in the trace.log:
_2020-12-05 14:08:56.865378 getRealtime *args=('ZAG.TO', 'last_price', 'yahoo') r='Yahoo.getRealtime(ZAG.TO, 21) - urlopen: 'charmap' codec can't encode character '\x84' in position 346582: character maps to <undefined>' 610.335 ms
2020-12-05 14:08:57.395496 getRealtime *args=('QQQ', 'last_price', 'yahoo') r='Yahoo.getRealtime(QQQ, 21) - urlopen: 'charmap' codec can't encode characters in position 357573-357574: character maps to <undefined>' 529.473 ms_

**Comment by cmallwitz** [comment]
Hmm, odd - looking at the code it could be that writing the files in .financials-extension fails due to character encoding issue.  What is the locale/language of your Windows installation? I will try make the code a bit more bullet proof to avoid any problems.

**Comment by cmallwitz** [comment]
I have uploaded a new version under https://github.com/cmallwitz/Financials-Extension/releases/tag/2.3.0 Could you give it a try?

**Comment by aradum** [comment]
Thank you for the update. It seems to work flawlessly now.

FYI, I think my locale was US English, but some settings might be in Canadian French or Canadian English.

Best,

**Comment by cmallwitz** [comment]
Anything else raise another issue!
