### ISSUE TITLE
Extension does not work in LibreOffice 7.6

### ISSUE THREAD

**Issue by vasanthaganeshk** [cmallwitz/Financials-Extension#92]
Version: 7.6.2.1
Platform: Fedora 39 x64

Error message:

![image](https://github.com/cmallwitz/Financials-Extension/assets/9608995/a7b052ad-5a07-4c4c-af98-4a1a8b05dec3)

**Comment by cmallwitz** [comment]
I will take a look - but I need to setup a VM first :-)

**Comment by cmallwitz** [comment]
I have updated some dependencies for Fedora - could you try the latest version 3.3.2?
