### ISSUE TITLE
Crashing on Mac when I drag formula to new cell

### ISSUE THREAD

**Issue by phrwn** [cmallwitz/Financials-Extension#93]
Everything's up-to-date (OS 14.2.1, LO 7.6.4.1, FME 3.3.2) but Calc hangs interminably every time I drag any FME formula to a new cell. I saw in the readme that I need LO SDK installed, but I don't remember ever doing so before and have been using this for ages. 

I downloaded the SDK which is just a folder of files. I can't figure out from the installation page how to actually install it and can't find instructions elsewhere online at all. I'm presuming this is the issue, but could be wrong, so posting here just in case.

**Comment by cmallwitz** [comment]
I wouldn't think you need the SDK unless you want to build the extension yourself.

Can you maybe explain a little more what is happening for you: if you have a cell with e.g =GETREALTIME("IBM:NYQ",21,"FT") you get a value (I get ~ 160 right now and it is changing when I refresh). What do you mean by dragging the formula? 

I can drag the lower/right hand corner of the cell with the formula (the little square) to one cell down and it copies the formula. You are saying it crashes on you doing that?

**Comment by phrwn** [comment]
Yes, exactly that - dragging the cell selection down to the next row was giving me the spinning wheel and Libreoffice going into a not responding state in the force quit applications menu.

However, coming back to it today it's now working. I pasted on your formula and it worked, so thought it might be the GETHISTORIC function, as that is all I use, but then that worked too. No idea why, I didn't do anything differently, it just works now. 

Thanks again for building this tool and supporting it.
