### ISSUE TITLE
Yahoo cookies. . . Again

### ISSUE THREAD

**Issue by myllo** [cmallwitz/Financials-Extension#94]
I have had this extension in use for some time now, both under Ubuntu and Windows 10.  

I had to reinstall windows 10, and now I cannot fetch data from Yahoo any more. Looks like they have changed something in the cookies handling once again.

The Ubuntu one still works, so this seems to relate to new cookies only.

=GETREALTIME("NDA-FI.HE";5;"YAHOO") returns N/A, and the yahoo-NDA-FI.HE.html file contains data only about the cookie selection alternatives. (in Finnish, , not included)

Steps to reproduce: 
close the file and the app, clear the .financials-extension directory, then relaunch the file.

**Comment by cmallwitz** [comment]
I actually updated Yahoo cookie handling over Christmas - hopefully properly re-fetching and confirming all cookies choices.

Can you try latest release version: [3.4.0](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.4.0) ?

**Comment by myllo** [comment]
Thank you.
Version 3.4.0 seems to work fine, for now..
Yahoo Finance seems to have a habit of making frequent changes to their
pages.


ma 15. tammik. 2024 klo 21.43 cmallwitz ***@***.***)
kirjoitti:

**Comment by cmallwitz** [comment]
Closing this - new version 3.6.1 is out.
