### ISSUE TITLE
completely  not working

### ISSUE THREAD

**Issue by techman2423** [cmallwitz/Financials-Extension#97]
Financial Market Extension  3.3.0 is no longer working for me.  It was working couple days ago last i opened it, got back to checking some things and have a bunch of NA in the fields. I have made no changes on my end.  Libre Office version 7.6.4.1 .
Update: i didn't realize there was an update to this extension. I've done that, however the issue persists.

Update again: I would delete this, but doesn't seem i can. I restarted Calc a couple times and the last time it started working again. I do not know, why....

apologies....

**Comment by techman2423** [comment]
i didn't realize there was an updated version, updated  to the latest extension and issue still persists

**Comment by techman2423** [comment]
Update again: I would delete this, but doesn't seem i can. I restarted Calc a couple times and the last time it started working again. I do not know, why....

apologies....

**Comment by JoshNewman** [comment]
I'm experiencing what sounds like the same thing.  Checking trace.log, it appears that all rows show the response _r='None'_ for calls to Yahoo -- for example : 

`2024-01-30 08:14:46.276869 getRealtime *args=('T', 24.0, 'YAHOO') r='None' 826.307 ms
2024-01-30 08:14:46.277088 getRealtime *args=('T', 21.0, 'YAHOO') r='None' 0.038 ms`
